import {
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArchiveBoxIcon,
  ArrowDownTrayIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightOnRectangleIcon,
  ArrowTrendingUpIcon,
  ArrowUpTrayIcon,
  ArrowUturnLeftIcon,
  ArrowsRightLeftIcon,
  BanknotesIcon,
  Bars3Icon,
  BellIcon,
  BellAlertIcon,
  BoldIcon,
  BoltIcon,
  BookOpenIcon,
  BuildingOfficeIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleLeftRightIcon,
  CheckIcon,
  CheckCircleIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClockIcon,
  CloudIcon,
  CloudArrowUpIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeIcon,
  CursorArrowRaysIcon,
  DevicePhoneMobileIcon,
  DocumentIcon,
  DocumentArrowUpIcon,
  DocumentChartBarIcon,
  DocumentDuplicateIcon,
  DocumentMagnifyingGlassIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  FingerPrintIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FunnelIcon,
  ChartBarSquareIcon,
  GiftIcon,
  GlobeAltIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  IdentificationIcon,
  InboxIcon,
  InformationCircleIcon,
  ItalicIcon,
  KeyIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  NewspaperIcon,
  NoSymbolIcon,
  PaperAirplaneIcon,
  PauseIcon,
  PencilIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlayIcon,
  PlusIcon,
  PlusCircleIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzlePieceIcon,
  QueueListIcon,
  ReceiptPercentIcon,
  ReceiptRefundIcon,
  RocketLaunchIcon,
  ScaleIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerXMarkIcon,
  Squares2X2Icon,
  SquaresPlusIcon,
  StarIcon,
  SwatchIcon,
  TableCellsIcon,
  TagIcon,
  TicketIcon,
  TrashIcon,
  TruckIcon,
  UserIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserPlusIcon,
  UsersIcon,
  VariableIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from "@heroicons/vue/20/solid";
import type { Component } from "vue";

export const heroicons: Record<string, Component> = {
  "adjustments-horizontal": AdjustmentsHorizontalIcon,
  "adjustments-vertical": AdjustmentsVerticalIcon,
  "archive-box": ArchiveBoxIcon,
  "arrow-down-tray": ArrowDownTrayIcon,
  "arrow-path": ArrowPathIcon,
  "arrow-path-rounded-square": ArrowPathRoundedSquareIcon,
  "arrow-right-on-rectangle": ArrowRightOnRectangleIcon,
  "arrow-trending-up": ArrowTrendingUpIcon,
  "arrow-up-tray": ArrowUpTrayIcon,
  "arrow-uturn-left": ArrowUturnLeftIcon,
  "arrows-right-left": ArrowsRightLeftIcon,
  banknotes: BanknotesIcon,
  "bars-3": Bars3Icon,
  bell: BellIcon,
  "bell-alert": BellAlertIcon,
  bold: BoldIcon,
  bolt: BoltIcon,
  "book-open": BookOpenIcon,
  "building-office": BuildingOfficeIcon,
  calculator: CalculatorIcon,
  "calendar-days": CalendarDaysIcon,
  "chart-bar": ChartBarIcon,
  "chart-pie": ChartPieIcon,
  "chat-bubble-left-right": ChatBubbleLeftRightIcon,
  check: CheckIcon,
  "check-circle": CheckCircleIcon,
  "chevron-up": ChevronUpIcon,
  "circle-stack": CircleStackIcon,
  "clipboard-document-check": ClipboardDocumentCheckIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  "code-bracket": CodeBracketIcon,
  "cog-6-tooth": Cog6ToothIcon,
  "cpu-chip": CpuChipIcon,
  "credit-card": CreditCardIcon,
  cube: CubeIcon,
  "cursor-arrow-rays": CursorArrowRaysIcon,
  "device-phone-mobile": DevicePhoneMobileIcon,
  document: DocumentIcon,
  "document-arrow-up": DocumentArrowUpIcon,
  "document-chart-bar": DocumentChartBarIcon,
  "document-duplicate": DocumentDuplicateIcon,
  "document-magnifying-glass": DocumentMagnifyingGlassIcon,
  "document-text": DocumentTextIcon,
  envelope: EnvelopeIcon,
  "envelope-open": EnvelopeOpenIcon,
  "exclamation-triangle": ExclamationTriangleIcon,
  eye: EyeIcon,
  "finger-print": FingerPrintIcon,
  folder: FolderIcon,
  "folder-open": FolderOpenIcon,
  "folder-plus": FolderPlusIcon,
  funnel: FunnelIcon,
  gauge: ChartBarSquareIcon,
  gift: GiftIcon,
  "globe-alt": GlobeAltIcon,
  hashtag: HashtagIcon,
  heart: HeartIcon,
  home: HomeIcon,
  identification: IdentificationIcon,
  inbox: InboxIcon,
  "information-circle": InformationCircleIcon,
  italic: ItalicIcon,
  key: KeyIcon,
  link: LinkIcon,
  "list-bullet": ListBulletIcon,
  "lock-closed": LockClosedIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  map: MapIcon,
  "map-pin": MapPinIcon,
  megaphone: MegaphoneIcon,
  newspaper: NewspaperIcon,
  "no-symbol": NoSymbolIcon,
  "paper-airplane": PaperAirplaneIcon,
  pencil: PencilIcon,
  "pencil-square": PencilSquareIcon,
  photo: PhotoIcon,
  play: PlayIcon,
  pause: PauseIcon,
  plus: PlusIcon,
  "plus-circle": PlusCircleIcon,
  "presentation-chart-bar": PresentationChartBarIcon,
  "presentation-chart-line": PresentationChartLineIcon,
  printer: PrinterIcon,
  "puzzle-piece": PuzzlePieceIcon,
  "queue-list": QueueListIcon,
  "receipt-percent": ReceiptPercentIcon,
  "receipt-refund": ReceiptRefundIcon,
  "rocket-launch": RocketLaunchIcon,
  scale: ScaleIcon,
  server: ServerIcon,
  share: ShareIcon,
  "shield-check": ShieldCheckIcon,
  "shield-exclamation": ShieldExclamationIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  signal: SignalIcon,
  sparkles: SparklesIcon,
  "speaker-x-mark": SpeakerXMarkIcon,
  "squares-2x2": Squares2X2Icon,
  "squares-plus": SquaresPlusIcon,
  star: StarIcon,
  swatch: SwatchIcon,
  "table-cells": TableCellsIcon,
  tag: TagIcon,
  ticket: TicketIcon,
  trash: TrashIcon,
  truck: TruckIcon,
  user: UserIcon,
  "user-circle": UserCircleIcon,
  "user-group": UserGroupIcon,
  "user-plus": UserPlusIcon,
  users: UsersIcon,
  variable: VariableIcon,
  "wrench-screwdriver": WrenchScrewdriverIcon,
  "x-mark": XMarkIcon,
};
