# Generated by Django 5.2.17 on 2026-08-06 07:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('monitoring_enabled', models.BooleanField(default=True)),
                ('sub2api_base_url', models.URLField(default='http://sub2api:8080')),
                ('sub2api_admin_token_encrypted', models.TextField(blank=True)),
                ('openai_account_id', models.BigIntegerField(blank=True, null=True)),
                ('quota_platform', models.CharField(default='openai', max_length=32)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=20)),
                ('verify_tls', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('cost_basis', models.CharField(choices=[('actual', '实际扣费'), ('standard', '标准计费')], default='actual', max_length=16)),
                ('initial_usd_per_percent', models.DecimalField(decimal_places=4, default=Decimal('16'), max_digits=12)),
                ('safety_factor', models.DecimalField(decimal_places=4, default=Decimal('0.95'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('conservative_percentile', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('rate_history_samples', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('local_poll_minutes', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(1440)])),
                ('progress_threshold_percent', models.DecimalField(decimal_places=3, default=Decimal('0.75'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('active_max_calibration_hours', models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(168)])),
                ('reset_proximity_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('stale_warning_hours', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(336)])),
                ('limit_warning_usd', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('recommendation_change_usd', models.DecimalField(decimal_places=4, default=Decimal('10'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_change_alert_percent', models.DecimalField(decimal_places=3, default=Decimal('5'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('notify_on_limit_exhausted', models.BooleanField(default=True)),
                ('notify_on_recommendation_change', models.BooleanField(default=False)),
                ('notify_on_rate_change', models.BooleanField(default=True)),
                ('notify_on_collection_error', models.BooleanField(default=True)),
                ('notification_cooldown_minutes', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10080)])),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('last_local_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_upstream_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('run_lease_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '服务设置',
                'verbose_name_plural': '服务设置',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sub2api_user_id', models.BigIntegerField(unique=True)),
                ('share_percent', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_owner', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('latest_weekly_usage_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('latest_weekly_limit_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('latest_selected_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '拼车参与者',
                'verbose_name_plural': '拼车参与者',
                'ordering': ['-is_owner', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotaCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField()),
                ('window_seconds', models.PositiveIntegerField(default=604800)),
                ('starts_at', models.DateTimeField()),
                ('resets_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-resets_at'],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'resets_at'), name='unique_account_reset_cycle')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('scheduled', '定时'), ('manual', '手动'), ('exhausted', '额度耗尽触发'), ('reset', '重置临近')], default='scheduled', max_length=16)),
                ('observed_at', models.DateTimeField()),
                ('upstream_used_percent', models.DecimalField(decimal_places=4, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('selected_total_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_standard_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('total_actual_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('delta_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('delta_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('sample_usd_per_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('effective_usd_per_percent', models.DecimalField(decimal_places=6, max_digits=18)),
                ('valid_sample', models.BooleanField(default=False)),
                ('sample_note', models.CharField(blank=True, max_length=255)),
                ('raw_window', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='monitor.quotacycle')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('limit_exhausted', '额度耗尽'), ('recommendation_changed', '建议变化'), ('rate_changed', '汇率变化'), ('collection_error', '采集失败'), ('test', '测试')], max_length=32)),
                ('severity', models.CharField(default='warning', max_length=16)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', '已发送'), ('skipped', '已跳过'), ('failed', '失败')], max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.participant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dedupe_key', '-created_at'], name='monitor_not_dedupe__21ac18_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('delta_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('charged_delta_percent', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('charged_cycle_percent', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('remaining_share_percent', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('platform_weekly_usage_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('platform_weekly_limit_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('recommended_weekly_limit_usd', models.DecimalField(decimal_places=4, max_digits=18)),
                ('recommendation_difference_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('needs_manual_update', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_snapshots', to='monitor.observation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitor.participant')),
            ],
            options={
                'ordering': ['participant_id'],
                'constraints': [models.UniqueConstraint(fields=('observation', 'participant'), name='unique_observation_participant')],
            },
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['cycle', '-observed_at'], name='monitor_obs_cycle_i_35779c_idx'),
        ),
    ]
