# Generated by Django 5.2.17 on 2026-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='quota_query_mode',
            field=models.CharField(choices=[('passive', '仅读取 Sub2API 被动快照'), ('direct', '调用上游账号额度接口')], default='passive', max_length=16),
        ),
    ]
