# Generated by Django 5.2.17 on 2026-08-06 07:41

import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_appsettings_quota_query_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='sub2api_base_url',
            field=models.CharField(default='http://host.docker.internal:8080', max_length=500, validators=[monitor.models.validate_service_url]),
        ),
    ]
