# Generated by Django 5.2.17 on 2026-08-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_appsettings_sub2api_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='email_provider',
            field=models.CharField(choices=[('smtp', 'SMTP'), ('resend', 'Resend')], default='smtp', max_length=16),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='resend_api_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='resend_from_email',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('success', models.BooleanField(default=False)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('webrtc_supported', models.BooleanField(blank=True, null=True)),
                ('webrtc_ips', models.JSONField(blank=True, default=list)),
                ('user_agent', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='login_event_time'), models.Index(fields=['success', '-created_at'], name='login_success_time')],
            },
        ),
        migrations.CreateModel(
            name='ParticipantUsageSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('weekly_usage_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('weekly_limit_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('selected_cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_samples', to='monitor.quotacycle')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_samples', to='monitor.participant')),
            ],
            options={
                'ordering': ['observed_at'],
                'indexes': [models.Index(fields=['participant', 'observed_at'], name='participant_usage_time')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'cycle', 'observed_at'), name='unique_participant_cycle_sample')],
            },
        ),
    ]
