# Generated by Django 5.2.17 on 2026-08-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_appsettings_email_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='quota_platform',
        ),
    ]
