# Generated by Django 5.2.17 on 2026-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_remove_appsettings_quota_platform'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quotacycle',
            name='unique_account_reset_cycle',
        ),
        migrations.AddConstraint(
            model_name='quotacycle',
            constraint=models.UniqueConstraint(fields=('account_id', 'resets_at', 'starts_at'), name='unique_account_reset_cycle'),
        ),
    ]
