# Generated by Django 5.2.17 on 2026-08-06 12:06

from django.db import migrations, models


def reset_stale_recommendations(apps, _schema_editor):
    """旧平台周限建议与用户余额不是同一概念，迁移后必须等待重新测算。"""
    participant_snapshot = apps.get_model("monitor", "ParticipantSnapshot")
    participant_snapshot.objects.update(
        needs_manual_update=False,
        reason="余额模型切换后等待下一次有效测算",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_remove_quotacycle_unique_account_reset_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='latest_weekly_limit_usd',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='latest_weekly_usage_usd',
        ),
        migrations.RemoveField(
            model_name='participantsnapshot',
            name='platform_weekly_limit_usd',
        ),
        migrations.RemoveField(
            model_name='participantsnapshot',
            name='platform_weekly_usage_usd',
        ),
        migrations.RemoveField(
            model_name='participantsnapshot',
            name='recommendation_difference_usd',
        ),
        migrations.RemoveField(
            model_name='participantsnapshot',
            name='recommended_weekly_limit_usd',
        ),
        migrations.RemoveField(
            model_name='participantusagesample',
            name='weekly_limit_usd',
        ),
        migrations.RemoveField(
            model_name='participantusagesample',
            name='weekly_usage_usd',
        ),
        migrations.AddField(
            model_name='participant',
            name='latest_balance_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='balance_difference_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='current_balance_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='recommended_balance_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantusagesample',
            name='balance_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.RunPython(
            reset_stale_recommendations,
            migrations.RunPython.noop,
        ),
    ]
