# Generated by Django 5.2.17 on 2026-08-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_remove_participant_latest_weekly_limit_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='next_local_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
