# Generated by Django 5.2 for the IP blocking feature.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0009_appsettings_daily_estimate_min_percent_span"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.GenericIPAddressField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("request", "服务器来源 IP"),
                            ("remote", "直连地址"),
                            ("webrtc", "WebRTC IP"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "login_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ip_blocks",
                        to="monitor.loginevent",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="blockedipaddress",
            constraint=models.UniqueConstraint(
                fields=("address", "source_type"),
                name="unique_blocked_ip_source",
            ),
        ),
        migrations.AddIndex(
            model_name="blockedipaddress",
            index=models.Index(
                fields=["source_type", "address"],
                name="blocked_ip_source_addr",
            ),
        ),
    ]
