# Generated by Django 5.2.17 on 2026-08-06 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_blockedipaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='quota_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='sub2api_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
