# Generated by Django 5.2.17 on 2026-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_participant_access_and_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='sub2api_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
