# Generated by Django 5.2.17 on 2026-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_participant_sub2api_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsnapshot',
            name='recommendation_applied',
            field=models.BooleanField(default=False),
        ),
    ]
