# Generated by Django 5.2.17 on 2026-08-09 12:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_fast_correction_request_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='conservative_percentile',
        ),
        migrations.RemoveField(
            model_name='appsettings',
            name='rate_history_samples',
        ),
        migrations.AddField(
            model_name='observation',
            name='capacity_lower_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='capacity_upper_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='estimated_used_percent',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='observation',
            name='model_diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='charged_percent_lower',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='charged_percent_upper',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='deterministic_balance_max_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='deterministic_balance_min_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='recommended_balance_max_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='recommended_balance_min_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
