# Generated by Django 5.2.17 on 2026-08-10 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_particle_filter_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAPIUsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('attribution_started_at', models.DateTimeField()),
                ('observed_at', models.DateTimeField()),
                ('cost_basis', models.CharField(max_length=16)),
                ('fast_correction_enabled', models.BooleanField(default=False)),
                ('participant_total_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('weekly_total_estimate_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('participant_weekly_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('api_keys', models.JSONField(default=list)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_snapshots', to='monitor.observation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_snapshots', to='monitor.participant')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['participant', '-observed_at'], name='api_usage_participant_time'), models.Index(fields=['account_id', 'attribution_started_at'], name='api_usage_account_cycle')],
            },
        ),
    ]
