# Generated by Django 5.2.17 on 2026-08-10 16:51

from django.db import migrations, models


def clear_legacy_query_windows(apps, _schema_editor):
    sample = apps.get_model("monitor", "Sub2APIUserUsageSample")
    sample.objects.update(window_started_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_participantapiusagesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='cost_window_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='cost_window_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='interval_actual_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='interval_cost_source',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='observation',
            name='interval_cost_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='interval_standard_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='normalized_actual_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='normalized_standard_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='interval_actual_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='interval_source',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='interval_standard_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='interval_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='normalized_actual_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='normalized_standard_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='window_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sub2apiuserusagesample',
            name='window_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            clear_legacy_query_windows,
            migrations.RunPython.noop,
        ),
    ]
