# Generated by Django 5.2.17 on 2026-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_observation_cost_window_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='readonly_api_key_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='readonly_api_key_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='readonly_api_key_hint',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
