# Generated by Django 5.2.17 on 2026-08-11 12:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_legacy_points(apps, _schema_editor):
    Observation = apps.get_model("monitor", "Observation")
    ParticipantSnapshot = apps.get_model("monitor", "ParticipantSnapshot")
    ParticipantUsageSample = apps.get_model(
        "monitor", "ParticipantUsageSample"
    )
    Sub2APIUserUsageSample = apps.get_model(
        "monitor", "Sub2APIUserUsageSample"
    )
    UsageSamplePoint = apps.get_model("monitor", "UsageSamplePoint")
    ParticipantBalanceSample = apps.get_model(
        "monitor", "ParticipantBalanceSample"
    )
    HistoryMaintenanceState = apps.get_model(
        "monitor", "HistoryMaintenanceState"
    )

    for observation in Observation.objects.order_by("account_id", "observed_at", "id").iterator():
        point, _created = UsageSamplePoint.objects.get_or_create(
            account_id=observation.account_id,
            observed_at=observation.observed_at,
            defaults={
                "window_started_at": observation.cost_window_started_at,
                "window_ended_at": observation.cost_window_ended_at,
                "window_resets_at": observation.upstream_resets_at,
                "account_standard_cost": observation.total_standard_cost,
                "account_actual_cost": observation.total_actual_cost,
                "interval_started_at": observation.interval_cost_started_at,
                "interval_standard_cost": observation.interval_standard_cost,
                "interval_actual_cost": observation.interval_actual_cost,
                "write_status": "legacy_unknown",
                "reconciliation_status": "unknown",
                "provenance": {"source": "legacy_0023"},
            },
        )
        observation.sample_point_id = point.id
        observation.save(update_fields=["sample_point"])

    for sample in Sub2APIUserUsageSample.objects.order_by(
        "account_id", "observed_at", "id"
    ).iterator():
        point, created = UsageSamplePoint.objects.get_or_create(
            account_id=sample.account_id,
            observed_at=sample.observed_at,
            defaults={
                "window_started_at": sample.window_started_at,
                "window_ended_at": sample.window_ended_at,
                "window_resets_at": sample.window_resets_at,
                "write_status": "legacy_unknown",
                "reconciliation_status": "unknown",
                "provenance": {"source": "legacy_0023"},
            },
        )
        if not created and point.window_resets_at is None:
            point.window_started_at = sample.window_started_at
            point.window_ended_at = sample.window_ended_at
            point.window_resets_at = sample.window_resets_at
            point.save(
                update_fields=[
                    "window_started_at",
                    "window_ended_at",
                    "window_resets_at",
                ]
            )
        sample.sample_point_id = point.id
        sample.save(update_fields=["sample_point"])

    for sample in ParticipantUsageSample.objects.order_by(
        "account_id", "observed_at", "id"
    ).iterator():
        point, _created = UsageSamplePoint.objects.get_or_create(
            account_id=sample.account_id,
            observed_at=sample.observed_at,
            defaults={
                "write_status": "legacy_unknown",
                "reconciliation_status": "unknown",
                "provenance": {"source": "legacy_0023"},
            },
        )
        sample.sample_point_id = point.id
        sample.save(update_fields=["sample_point"])
        ParticipantBalanceSample.objects.get_or_create(
            point_id=point.id,
            participant_id=sample.participant_id,
            provenance="legacy_participant_usage",
            defaults={
                "balance_usd": sample.balance_usd,
                "captured_at": sample.observed_at,
            },
        )

    for snapshot in ParticipantSnapshot.objects.exclude(
        current_balance_usd__isnull=True
    ).select_related("observation").iterator():
        point_id = snapshot.observation.sample_point_id
        if point_id is None:
            continue
        ParticipantBalanceSample.objects.get_or_create(
            point_id=point_id,
            participant_id=snapshot.participant_id,
            provenance="legacy_observation_snapshot",
            defaults={
                "balance_usd": snapshot.current_balance_usd,
                "captured_at": snapshot.observation.observed_at,
            },
        )

    for point in UsageSamplePoint.objects.order_by("id").iterator():
        users = Sub2APIUserUsageSample.objects.filter(sample_point_id=point.id)
        standard = sum(
            users.values_list("total_standard_cost", flat=True),
            0,
        )
        actual = sum(
            users.values_list("total_actual_cost", flat=True),
            0,
        )
        updates = []
        if point.account_standard_cost is not None:
            point.residual_standard_cost = point.account_standard_cost - standard
            updates.append("residual_standard_cost")
        if point.account_actual_cost is not None:
            point.residual_actual_cost = point.account_actual_cost - actual
            updates.append("residual_actual_cost")
        if updates:
            point.save(update_fields=updates)
        HistoryMaintenanceState.objects.get_or_create(
            account_id=point.account_id
        )


def no_reverse_backfill(_apps, _schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_appsettings_readonly_api_key_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMaintenanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(unique=True)),
                ('fact_revision', models.PositiveBigIntegerField(default=0)),
                ('fence_token', models.PositiveBigIntegerField(default=0)),
                ('lease_owner', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='appsettings',
            name='sub2api_usage_log_query_horizon_days',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36500)]),
        ),
        migrations.CreateModel(
            name='HistoricalRebuildRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('mode', models.CharField(choices=[('audit_replay', '本地审计并重放'), ('verified_remote_repair', '远端验证修复')], max_length=32)),
                ('state', models.CharField(choices=[('generating', '生成中'), ('ready', '可应用'), ('blocked', '已阻断'), ('stale', '已过期'), ('applying', '应用中'), ('applied', '已应用'), ('rolled_back', '已回滚'), ('failed', '失败')], default='generating', max_length=16)),
                ('base_revision', models.PositiveBigIntegerField()),
                ('result_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('rollback_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cutoff', models.DateTimeField(blank=True, null=True)),
                ('requested_started_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ended_at', models.DateTimeField(blank=True, null=True)),
                ('source_digest', models.CharField(max_length=64)),
                ('plan_digest', models.CharField(blank=True, max_length=64)),
                ('algorithm_version', models.CharField(max_length=64)),
                ('build_id', models.CharField(max_length=128)),
                ('config_digest', models.CharField(max_length=64)),
                ('participant_policy_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('patch_summary', models.JSONField(blank=True, default=dict)),
                ('before_source_hash', models.CharField(blank=True, max_length=64)),
                ('after_source_hash', models.CharField(blank=True, max_length=64)),
                ('before_observable_hash', models.CharField(blank=True, max_length=64)),
                ('after_observable_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account_id', '-created_at'], name='history_run_account_time')],
            },
        ),
        migrations.CreateModel(
            name='UsageSamplePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('observed_at', models.DateTimeField()),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('window_ended_at', models.DateTimeField(blank=True, null=True)),
                ('window_resets_at', models.DateTimeField(blank=True, null=True)),
                ('capture_started_at', models.DateTimeField(blank=True, null=True)),
                ('capture_finished_at', models.DateTimeField(blank=True, null=True)),
                ('account_standard_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('account_actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('interval_started_at', models.DateTimeField(blank=True, null=True)),
                ('interval_standard_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('interval_actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('residual_standard_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('residual_actual_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('expected_user_count', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_user_digest', models.CharField(blank=True, max_length=64)),
                ('write_status', models.CharField(choices=[('complete', '本地写入完整'), ('legacy_unknown', '旧数据完整性未知')], default='legacy_unknown', max_length=24)),
                ('reconciliation_status', models.CharField(choices=[('reconciled', '账号与用户合计一致'), ('residual', '存在显式未分配残差'), ('unknown', '无法核对'), ('conflict', '核对冲突')], default='unknown', max_length=16)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('fact_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['observed_at', 'id'],
                'indexes': [models.Index(fields=['account_id', 'observed_at'], name='usage_point_account_time')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'observed_at'), name='unique_usage_sample_point')],
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='sample_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='monitor.usagesamplepoint'),
        ),
        migrations.AddField(
            model_name='participantusagesample',
            name='sample_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_usage_samples', to='monitor.usagesamplepoint'),
        ),
        migrations.AddField(
            model_name='sub2apiuserusagesample',
            name='sample_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_samples', to='monitor.usagesamplepoint'),
        ),
        migrations.CreateModel(
            name='ParticipantBalanceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('captured_at', models.DateTimeField()),
                ('provenance', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_samples', to='monitor.participant')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_samples', to='monitor.usagesamplepoint')),
            ],
            options={
                'ordering': ['captured_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('point', 'participant', 'provenance'), name='unique_point_balance_source')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRebuildPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('observation_cost', '观测/采样点成本'), ('user_cost', '用户成本'), ('fast_fact', 'FAST 事实')], max_length=24)),
                ('sub2api_user_id', models.BigIntegerField(blank=True, null=True)),
                ('natural_key', models.JSONField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('before_payload', models.JSONField(blank=True, null=True)),
                ('after_payload', models.JSONField()),
                ('required_coverage_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rebuild_patches', to='monitor.observation')),
                ('user_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rebuild_patches', to='monitor.sub2apiuserusagesample')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='monitor.historicalrebuildrun')),
                ('sample_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rebuild_patches', to='monitor.usagesamplepoint')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('run', 'sequence'), name='unique_rebuild_patch_sequence'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'observation_cost'), ('sub2api_user_id__isnull', True)), models.Q(('kind', 'user_cost'), ('sub2api_user_id__isnull', False)), models.Q(('kind', 'fast_fact'), ('observation__isnull', False), ('sub2api_user_id__isnull', True)), _connector='OR'), name='rebuild_patch_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRebuildCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('dimension', models.CharField(choices=[('account_cost', '账号成本'), ('user_cost', '用户成本'), ('fast_cost', 'FAST 成本'), ('request_count', '请求数'), ('api_key', 'API Key')], max_length=24)),
                ('status', models.CharField(choices=[('verified', '已验证'), ('verified_empty', '已验证为空'), ('captured_local', '本地完整写入'), ('out_of_scope', '目标范围外'), ('policy_only', '仅策略推定'), ('unknown', '未知'), ('unavailable', '不可用')], max_length=24)),
                ('evidence_type', models.CharField(max_length=64)),
                ('evidence_digest', models.CharField(blank=True, max_length=64)),
                ('blocker', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rows', to='monitor.historicalrebuildrun')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rebuild_coverage_rows', to='monitor.usagesamplepoint')),
            ],
            options={
                'ordering': ['started_at', 'dimension', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'point', 'started_at', 'ended_at', 'dimension'), name='unique_rebuild_coverage'), models.CheckConstraint(condition=models.Q(('ended_at__gt', models.F('started_at'))), name='coverage_nonempty_range')],
            },
        ),
        migrations.RunPython(
            backfill_legacy_points,
            no_reverse_backfill,
        ),
    ]
