# Generated by Django 5.2.17 on 2026-08-11 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_history_maintenance_control_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantBalanceOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField(db_index=True)),
                ('base_revision', models.PositiveBigIntegerField()),
                ('sub2api_user_id', models.BigIntegerField()),
                ('requested_balance_usd', models.DecimalField(decimal_places=6, max_digits=18)),
                ('confirmed_balance_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('state', models.CharField(choices=[('prepared', '已持久化，尚未确认远端结果'), ('reconciliation_required', '远端结果不确定，等待对账'), ('remote_confirmed', '远端已确认，等待本地提交'), ('committed', '远端与本地均已提交')], default='prepared', max_length=32)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remote_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_operations', to='monitor.participant')),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='balance_operation', to='monitor.participantsnapshot')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['account_id', 'state'], name='balance_op_account_state')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('confirmed_balance_usd__isnull', True), ('state__in', ('prepared', 'reconciliation_required'))), models.Q(('confirmed_balance_usd__isnull', False), ('state__in', ('remote_confirmed', 'committed'))), _connector='OR'), name='balance_op_state_payload')],
            },
        ),
    ]
