# Generated by Django 5.2.17 on 2026-08-14 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_participantbalanceoperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrebuildrun',
            name='after_observable_hash',
        ),
        migrations.RemoveField(
            model_name='historicalrebuildrun',
            name='after_source_hash',
        ),
    ]
