# Generated by Django 5.2.17 on 2026-08-16 16:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_manual_start_intervals(apps, _schema_editor):
    Observation = apps.get_model("monitor", "Observation")
    for observation in Observation.objects.filter(is_manual_start=True).iterator():
        observation.manual_start_end_id = observation.id
        observation.save(update_fields=["manual_start_end"])


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_remove_verified_remote_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='manual_start_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='monitor.observation'),
        ),
        migrations.RunPython(
            migrate_manual_start_intervals,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_manual_start', False), ('manual_start_end__isnull', True)), models.Q(('is_manual_start', True), ('manual_start_end__isnull', False)), _connector='OR'), name='manual_start_end_matches_flag'),
        ),
    ]
