# Generated by Django 5.2.17 on 2026-08-18 10:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_operation_sources(apps, _schema_editor):
    MonitoredAccount = apps.get_model("monitor", "MonitoredAccount")
    Operation = apps.get_model("monitor", "ParticipantBalanceOperation")
    Source = apps.get_model("monitor", "ParticipantBalanceOperationSource")

    for operation in Operation.objects.order_by("created_at", "id"):
        account, _created = MonitoredAccount.objects.get_or_create(
            external_account_id=operation.account_id,
            defaults={
                "name": f"OpenAI 账号 {operation.account_id}",
                "enabled": False,
            },
        )
        Source.objects.create(
            operation_id=operation.id,
            account_id=account.id,
            account_external_id=operation.account_id,
            base_revision=operation.base_revision,
            snapshot_id=operation.snapshot_id,
            contribution_usd=operation.requested_balance_usd,
        )


def restore_operation_fields(apps, _schema_editor):
    Operation = apps.get_model("monitor", "ParticipantBalanceOperation")
    Source = apps.get_model("monitor", "ParticipantBalanceOperationSource")

    for operation in Operation.objects.order_by("created_at", "id"):
        source = Source.objects.filter(operation_id=operation.id).order_by("id").first()
        if source is None:
            continue
        operation.account_id = source.account_external_id
        operation.base_revision = source.base_revision
        operation.snapshot_id = source.snapshot_id
        operation.save(
            update_fields=["account_id", "base_revision", "snapshot"]
        )


class Migration(migrations.Migration):
    dependencies = [("monitor", "0029_sub2api_multi_account")]

    operations = [
        migrations.CreateModel(
            name="ParticipantBalanceOperationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_external_id",
                    models.BigIntegerField(db_index=True),
                ),
                ("base_revision", models.PositiveBigIntegerField()),
                (
                    "contribution_usd",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_operation_sources",
                        to="monitor.monitoredaccount",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="monitor.participantbalanceoperation",
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_operation_source",
                        to="monitor.participantsnapshot",
                    ),
                ),
            ],
            options={"ordering": ["account_external_id", "id"]},
        ),
        migrations.RunPython(migrate_operation_sources, restore_operation_fields),
        migrations.RemoveIndex(
            model_name="participantbalanceoperation",
            name="balance_op_account_state",
        ),
        migrations.RemoveField(
            model_name="participantbalanceoperation",
            name="account_id",
        ),
        migrations.RemoveField(
            model_name="participantbalanceoperation",
            name="base_revision",
        ),
        migrations.RemoveField(
            model_name="participantbalanceoperation",
            name="snapshot",
        ),
        migrations.AddIndex(
            model_name="participantbalanceoperation",
            index=models.Index(
                fields=["participant", "state"],
                name="balance_op_participant_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="participantbalanceoperationsource",
            constraint=models.UniqueConstraint(
                fields=("operation", "account_external_id"),
                name="unique_balance_op_account",
            ),
        ),
    ]
