# Generated by Django 5.2.17 on 2026-08-18 15:26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


def migrate_pooled_contracts(apps, _schema_editor):
    Participant = apps.get_model("monitor", "Participant")
    AccountParticipant = apps.get_model("monitor", "AccountParticipant")
    MonitoredAccount = apps.get_model("monitor", "MonitoredAccount")

    participants = list(Participant.objects.order_by("id"))
    accounts = list(MonitoredAccount.objects.order_by("id"))
    existing_pairs = set(
        AccountParticipant.objects.values_list("account_id", "participant_id")
    )
    missing_rows = []
    for participant in participants:
        rows = list(
            AccountParticipant.objects.filter(participant_id=participant.id).order_by(
                "account_id",
                "id",
            )
        )
        active_rows = [row for row in rows if row.enabled]
        policies = active_rows or rows
        shares = {row.share_percent for row in policies}
        owners = {row.is_owner for row in policies}
        if len(shares) > 1 or len(owners) > 1:
            raise RuntimeError(
                "无法自动迁移参与者 "
                f"{participant.id} 的混池合同：各账号权益或车主身份不一致；"
                "请先在旧版本中统一后重试"
            )
        participant.share_percent = next(iter(shares), Decimal("0"))
        participant.is_owner = next(iter(owners), False)
        for account in accounts:
            if (account.id, participant.id) in existing_pairs:
                continue
            missing_rows.append(
                AccountParticipant(
                    account_id=account.id,
                    participant_id=participant.id,
                    share_percent=participant.share_percent,
                    is_owner=participant.is_owner,
                    enabled=participant.enabled,
                )
            )
    if participants:
        Participant.objects.bulk_update(
            participants,
            ["share_percent", "is_owner"],
        )
    if missing_rows:
        AccountParticipant.objects.bulk_create(missing_rows)


def restore_account_contracts(apps, _schema_editor):
    Participant = apps.get_model("monitor", "Participant")
    AccountParticipant = apps.get_model("monitor", "AccountParticipant")

    participants = {
        participant.id: participant
        for participant in Participant.objects.order_by("id")
    }
    rows = list(AccountParticipant.objects.order_by("id"))
    for row in rows:
        participant = participants[row.participant_id]
        row.share_percent = participant.share_percent
        row.is_owner = participant.is_owner
        row.enabled = participant.enabled
    if rows:
        AccountParticipant.objects.bulk_update(
            rows,
            ["share_percent", "is_owner", "enabled"],
        )


class Migration(migrations.Migration):
    dependencies = [("monitor", "0030_aggregate_balance_operations")]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participant",
            name="share_percent",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.RunPython(migrate_pooled_contracts, restore_account_contracts),
        migrations.RemoveField(
            model_name="accountparticipant",
            name="enabled",
        ),
        migrations.RemoveField(
            model_name="accountparticipant",
            name="is_owner",
        ),
        migrations.RemoveField(
            model_name="accountparticipant",
            name="share_percent",
        ),
        migrations.AlterField(
            model_name="participant",
            name="share_percent",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=7,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterModelOptions(
            name="accountparticipant",
            options={"ordering": ["account_id", "participant_id"]},
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["-is_owner", "id"],
                "verbose_name": "拼车参与者",
                "verbose_name_plural": "拼车参与者",
            },
        ),
    ]
