# Generated by Django 5.2.17 on 2026-08-23 07:56

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_global_contract_to_default_pool(apps, _schema_editor):
    MonitoredAccount = apps.get_model("monitor", "MonitoredAccount")
    Participant = apps.get_model("monitor", "Participant")
    ParticipantSnapshot = apps.get_model("monitor", "ParticipantSnapshot")
    PoolParticipant = apps.get_model("monitor", "PoolParticipant")
    QuotaPool = apps.get_model("monitor", "QuotaPool")

    accounts = list(MonitoredAccount.objects.order_by("id"))
    participants = list(Participant.objects.order_by("id"))
    snapshots = list(ParticipantSnapshot.objects.order_by("id"))
    if not accounts and not participants and not snapshots:
        return

    pool = QuotaPool.objects.create(name="默认混池")
    MonitoredAccount.objects.filter(pk__in=[account.pk for account in accounts]).update(
        pool_id=pool.pk
    )
    PoolParticipant.objects.bulk_create(
        [
            PoolParticipant(
                pool_id=pool.pk,
                participant_id=participant.pk,
                share_percent=participant.share_percent,
            )
            for participant in participants
        ]
    )

    # 旧模型只有一份覆盖全部账号的全局合同。即使某个历史观测对应的
    # 监控账号后来已被删除，它的快照仍属于这份默认合同，不能留空。
    for snapshot in snapshots:
        snapshot_pool = pool
        snapshot.quota_pool_id = snapshot_pool.pk
        snapshot.quota_pool_name = snapshot_pool.name
        snapshot.pool_contract_revision = snapshot_pool.contract_revision
    if snapshots:
        ParticipantSnapshot.objects.bulk_update(
            snapshots,
            ["quota_pool_id", "quota_pool_name", "pool_contract_revision"],
        )


def restore_global_contract(apps, _schema_editor):
    MonitoredAccount = apps.get_model("monitor", "MonitoredAccount")
    Participant = apps.get_model("monitor", "Participant")
    PoolParticipant = apps.get_model("monitor", "PoolParticipant")
    QuotaPool = apps.get_model("monitor", "QuotaPool")

    account_pool_ids = set(
        MonitoredAccount.objects.order_by()
        .values_list("pool_id", flat=True)
        .distinct()
    )
    pool_ids = account_pool_ids or set(
        QuotaPool.objects.order_by().values_list("id", flat=True)
    )
    for participant in Participant.objects.order_by("id"):
        shares_by_pool_id = dict(
            PoolParticipant.objects.filter(
                participant_id=participant.pk,
                pool_id__in=pool_ids,
            ).values_list("pool_id", "share_percent")
        )
        shares = {
            shares_by_pool_id.get(pool_id, Decimal("0"))
            for pool_id in pool_ids
        }
        if len(shares) > 1:
            raise RuntimeError(
                "无法降级包含不同池份额的参与者合同；请先统一各池份额"
            )
        participant.share_percent = next(iter(shares), Decimal("0"))
        participant.save(update_fields=["share_percent"])


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0035_fast_correction_model_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("contract_revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "额度池",
                "verbose_name_plural": "额度池",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="participantsnapshot",
            name="pool_contract_revision",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantsnapshot",
            name="quota_pool_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantsnapshot",
            name="quota_pool_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="monitoredaccount",
            name="pool",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="monitor.quotapool",
            ),
        ),
        migrations.CreateModel(
            name="PoolParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_percent",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_allocations",
                        to="monitor.participant",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="monitor.quotapool",
                    ),
                ),
            ],
            options={
                "ordering": ["pool_id", "participant_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pool", "participant"),
                        name="unique_pool_participant",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="participant",
            name="share_percent",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.RunPython(
            migrate_global_contract_to_default_pool,
            restore_global_contract,
        ),
        migrations.RemoveField(
            model_name="participant",
            name="share_percent",
        ),
    ]
