# Generated by Django 5.2.17 on 2026-08-23 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0036_quota_pools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredaccount',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='monitor.quotapool'),
        ),
    ]
