# Generated by Django 5.2.17 on 2026-08-23 09:00

from django.db import migrations, models


def _backfill_batch(ParticipantSnapshot, Sub2APIUserUsageSample, snapshots):
    point_ids = {
        snapshot.observation.sample_point_id
        for snapshot in snapshots
        if snapshot.observation.sample_point_id is not None
    }
    evidence = set(
        Sub2APIUserUsageSample.objects.filter(
            sample_point_id__in=point_ids,
        ).values_list("sample_point_id", "sub2api_user_id")
    )
    verified = []
    for snapshot in snapshots:
        identity = (
            snapshot.observation.sample_point_id,
            snapshot.participant.sub2api_user_id,
        )
        if identity in evidence:
            snapshot.source_sub2api_user_id = identity[1]
            verified.append(snapshot)
    if verified:
        ParticipantSnapshot.objects.bulk_update(
            verified,
            ["source_sub2api_user_id"],
        )


def populate_snapshot_user_ids(apps, _schema_editor):
    ParticipantSnapshot = apps.get_model("monitor", "ParticipantSnapshot")
    Sub2APIUserUsageSample = apps.get_model(
        "monitor",
        "Sub2APIUserUsageSample",
    )
    pending = []
    snapshots = (
        ParticipantSnapshot.objects.filter(source_sub2api_user_id__isnull=True)
        .select_related("participant", "observation")
        .order_by("id")
    )
    for snapshot in snapshots.iterator(chunk_size=500):
        pending.append(snapshot)
        if len(pending) == 500:
            _backfill_batch(
                ParticipantSnapshot,
                Sub2APIUserUsageSample,
                pending,
            )
            pending.clear()
    if pending:
        _backfill_batch(
            ParticipantSnapshot,
            Sub2APIUserUsageSample,
            pending,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0037_require_account_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsnapshot",
            name="source_sub2api_user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            populate_snapshot_user_ids,
            migrations.RunPython.noop,
        ),
    ]
