# Generated by Django 5.2.17 on 2026-08-23 09:30

import django.db.models.deletion
from django.db import migrations, models


def populate_applied_shares(apps, _schema_editor):
    OperationSource = apps.get_model(
        "monitor",
        "ParticipantBalanceOperationSource",
    )
    pending = []
    sources = (
        OperationSource.objects.filter(share_percent__isnull=True)
        .select_related("snapshot")
        .order_by("id")
    )
    for source in sources.iterator(chunk_size=500):
        source.share_percent = source.snapshot.share_percent
        pending.append(source)
        if len(pending) == 500:
            OperationSource.objects.bulk_update(
                pending,
                ["share_percent"],
            )
            pending.clear()
    if pending:
        OperationSource.objects.bulk_update(
            pending,
            ["share_percent"],
        )


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0038_snapshot_source_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantbalanceoperationsource",
            name="share_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=7,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_applied_shares,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="participantbalanceoperationsource",
            name="share_percent",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name="participantbalanceoperationsource",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balance_operation_sources",
                to="monitor.participantsnapshot",
            ),
        ),
    ]
