# Generated by Django 5.2.17 on 2026-08-23 15:52

from django.conf import settings
from django.db import migrations, models


def preserve_existing_account_status_access(apps, _schema_editor):
    user_app, user_model = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app, user_model)
    MonitoredAccount = apps.get_model("monitor", "MonitoredAccount")
    PageAccess = apps.get_model("monitor", "SystemUserPageAccess")
    through_model = MonitoredAccount.authorized_users.through
    account_ids = list(
        MonitoredAccount.objects.order_by().values_list("id", flat=True)
    )
    user_ids = list(
        User.objects.filter(
            id__in=PageAccess.objects.filter(
                page_code="account_status"
            ).values("user_id"),
            is_staff=False,
            is_superuser=False,
        )
        .order_by()
        .values_list("id", flat=True)
    )
    through_model.objects.bulk_create(
        [
            through_model(monitoredaccount_id=account_id, user_id=user_id)
            for user_id in user_ids
            for account_id in account_ids
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0039_applied_projection_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredaccount',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='visible_monitored_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            preserve_existing_account_status_access,
            migrations.RunPython.noop,
        ),
    ]
