# Generated by Django 5.2.17 on 2026-08-24 11:31

from django.db import migrations, models


def remove_settings_page_grants(apps, _schema_editor):
    page_access = apps.get_model("monitor", "SystemUserPageAccess")
    page_access.objects.filter(page_code="settings").delete()


def restore_settings_page_grants(apps, _schema_editor):
    page_access = apps.get_model("monitor", "SystemUserPageAccess")
    user_model = page_access._meta.get_field("user").remote_field.model
    page_access.objects.bulk_create(
        [
            page_access(user_id=user_id, page_code="settings")
            for user_id in user_model.objects.filter(
                is_staff=False,
                is_superuser=False,
            ).values_list("id", flat=True)
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0041_system_user_api_key"),
    ]

    operations = [
        migrations.RunPython(
            remove_settings_page_grants,
            restore_settings_page_grants,
        ),
        migrations.AlterField(
            model_name="systemuserpageaccess",
            name="page_code",
            field=models.CharField(
                choices=[
                    ("dashboard", "额度总览"),
                    ("account_status", "账号状态"),
                    ("participants", "参与者"),
                    ("system_users", "系统用户"),
                    ("observations", "观测记录"),
                    ("particle_filter", "粒子轨迹"),
                    ("statistics", "额度统计"),
                    ("notifications", "通知记录"),
                    ("login_records", "登录记录"),
                    ("tutorial", "使用教程"),
                ],
                max_length=32,
            ),
        ),
    ]
