# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0042_automatic_system_user_settings_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoredaccount",
            name="detected_plan_type",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="monitoredaccount",
            name="quota_profile",
            field=models.CharField(
                choices=[
                    ("auto", "自动识别 Plus / Pro"),
                    ("plus", "ChatGPT Plus"),
                    ("pro_5x", "ChatGPT Pro 5X"),
                    ("pro_20x", "ChatGPT Pro 20X"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
    ]
