# Generated by Django 5.2.17 on 2026-08-27

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0043_monitoredaccount_quota_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoredaccount",
            name="capacity_max_usd_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[
                    MinValueValidator(Decimal("1")),
                    MaxValueValidator(Decimal("50000")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="monitoredaccount",
            name="capacity_min_usd_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[
                    MinValueValidator(Decimal("1")),
                    MaxValueValidator(Decimal("50000")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="monitoredaccount",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        capacity_min_usd_override__isnull=True,
                        capacity_max_usd_override__isnull=True,
                    )
                    | models.Q(
                        capacity_min_usd_override__isnull=False,
                        capacity_max_usd_override__isnull=False,
                        capacity_min_usd_override__gte=Decimal("1"),
                        capacity_max_usd_override__lte=Decimal("50000"),
                        capacity_min_usd_override__lt=models.F(
                            "capacity_max_usd_override"
                        ),
                    )
                ),
                name="account_capacity_range_valid",
            ),
        ),
    ]
