# Generated by Django 5.2.17 on 2026-08-28 17:30

import django.core.validators
import django.db.models.deletion
import monitor.cpa.pricing
import monitor.models.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0044_monitoredaccount_capacity_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPAUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_fingerprint', models.CharField(max_length=64, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('model', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('api_key_hash', models.CharField(blank=True, max_length=64)),
                ('api_key_hint', models.CharField(blank=True, max_length=4)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('failed', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveBigIntegerField(default=0)),
                ('ttft_ms', models.PositiveBigIntegerField(default=0)),
                ('requested_service_tier', models.CharField(blank=True, max_length=32)),
                ('response_service_tier', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CPA 用量事件',
                'verbose_name_plural': 'CPA 用量事件',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='monitoredaccount',
            options={'ordering': ['name', 'provider', 'external_account_id', 'cpa_auth_index'], 'verbose_name': '监控上游账号', 'verbose_name_plural': '监控上游账号'},
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_base_url',
            field=models.CharField(default='http://host.docker.internal:8317', max_length=500, validators=[monitor.models.validators.validate_service_url]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_double_billing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_double_billing_multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('2'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_double_billing_threshold_tokens',
            field=models.PositiveIntegerField(default=272000, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_fast_multiplier',
            field=models.DecimalField(decimal_places=4, default=Decimal('2.5'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_management_key_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='cpa_model_pricing',
            field=models.JSONField(default=monitor.cpa.pricing.default_cpa_model_pricing, validators=[monitor.cpa.pricing.validate_cpa_model_pricing]),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='cpa_auth_index',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='monitoredaccount',
            name='provider',
            field=models.CharField(choices=[('sub2api', 'Sub2API'), ('cpa', 'CPA')], default='sub2api', max_length=16),
        ),
        migrations.AlterField(
            model_name='monitoredaccount',
            name='external_account_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='monitoredaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cpa_auth_index__isnull', True), ('external_account_id__isnull', False), ('provider', 'sub2api')), models.Q(('cpa_auth_index__isnull', False), ('external_account_id__isnull', True), ('provider', 'cpa')), _connector='OR'), name='account_provider_identity_valid'),
        ),
        migrations.AddField(
            model_name='cpausageevent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpa_usage_events', to='monitor.monitoredaccount'),
        ),
        migrations.AddIndex(
            model_name='cpausageevent',
            index=models.Index(fields=['account', 'occurred_at'], name='monitor_cpa_account_9030c9_idx'),
        ),
        migrations.AddIndex(
            model_name='cpausageevent',
            index=models.Index(fields=['account', 'api_key_hash', 'occurred_at'], name='monitor_cpa_account_d40809_idx'),
        ),
    ]
