# Generated by Django 5.2.17 on 2026-08-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0045_cpausageevent_alter_monitoredaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPACollectorState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('connected', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_persisted_at', models.DateTimeField(blank=True, null=True)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CPA collector state',
                'verbose_name_plural': 'CPA collector state',
            },
        ),
    ]
