# Generated by Django 5.2.17 on 2026-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0046_cpacollectorstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='source',
            field=models.CharField(choices=[('scheduled', '定时'), ('manual', '手动'), ('exhausted', '额度耗尽触发'), ('reset', '重置临近'), ('cpa_subscription_opened', 'CPA 订阅连接'), ('cpa_subscription_closed', 'CPA 订阅断开')], default='scheduled', max_length=32),
        ),
    ]
