# Generated by Django 5.2.17 on 2026-08-29 10:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_collection_intervals(apps, _schema_editor):
    Account = apps.get_model("monitor", "MonitoredAccount")
    Observation = apps.get_model("monitor", "Observation")
    CollectionInterval = apps.get_model(
        "monitor",
        "CPAAccountCollectionInterval",
    )

    for account in Account.objects.filter(provider="cpa").iterator():
        observations = list(
            Observation.objects.filter(account_id=-account.id).order_by(
                "observed_at",
                "id",
            )
        )
        if not observations:
            continue

        def marker(observation):
            raw = (
                observation.raw_window
                if isinstance(observation.raw_window, dict)
                else {}
            )
            boundary = raw.get("connection_boundary")
            if boundary in {"opened", "closed"}:
                return boundary, raw
            if raw.get("connection_baseline"):
                return "opened", raw
            return None, raw

        current = None
        for observation in observations:
            boundary, raw = marker(observation)
            if boundary is None:
                continue
            boundary_id = str(raw.get("connection_boundary_id") or "")
            session_key = ""
            for separator in (
                ":opened:",
                ":closed:",
                ":interrupted-close:",
            ):
                if separator in boundary_id:
                    session_key = boundary_id.split(separator, 1)[0]
                    break
            session_key = (session_key or f"legacy-{observation.id}")[:64]

            if boundary == "opened":
                if current is not None:
                    current.disconnected_at = observation.observed_at
                    current.end_reliable = False
                    current.save(
                        update_fields=["disconnected_at", "end_reliable"]
                    )
                current = CollectionInterval.objects.create(
                    account_id=account.id,
                    session_key=session_key,
                    connected_at=observation.observed_at,
                    opening_observation_id=observation.id,
                )
                continue

            if current is None:
                continue
            current.disconnected_at = observation.observed_at
            current.end_reliable = bool(
                raw.get("connection_boundary_reliable", True)
            )
            current.closing_observation_id = observation.id
            current.save(
                update_fields=[
                    "disconnected_at",
                    "end_reliable",
                    "closing_observation",
                ]
            )
            current = None


def reverse_legacy_collection_intervals(apps, _schema_editor):
    CollectionInterval = apps.get_model(
        "monitor",
        "CPAAccountCollectionInterval",
    )
    CollectionInterval.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0047_expand_observation_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPAAccountCollectionInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('connected_at', models.DateTimeField(db_index=True)),
                ('disconnected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_reliable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpa_collection_intervals', to='monitor.monitoredaccount')),
                ('closing_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.observation')),
                ('opening_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitor.observation')),
            ],
            options={
                'verbose_name': 'CPA 账号采集区间',
                'verbose_name_plural': 'CPA 账号采集区间',
                'ordering': ['connected_at', 'id'],
                'indexes': [models.Index(fields=['account', 'connected_at'], name='cpa_collection_account_start')],
                'constraints': [
                    models.UniqueConstraint(fields=('account', 'session_key'), name='unique_cpa_account_collection_session'),
                    models.UniqueConstraint(condition=models.Q(('disconnected_at__isnull', True)), fields=('account',), name='unique_open_cpa_collection_interval'),
                    models.CheckConstraint(condition=models.Q(('disconnected_at__isnull', True), ('disconnected_at__gte', models.F('connected_at')), _connector='OR'), name='cpa_collection_end_not_before_start'),
                ],
            },
        ),
        migrations.RunPython(
            migrate_legacy_collection_intervals,
            reverse_legacy_collection_intervals,
        ),
        migrations.AlterField(
            model_name="observation",
            name="source",
            field=models.CharField(
                choices=[
                    ("scheduled", "定时"),
                    ("manual", "手动"),
                    ("exhausted", "额度耗尽触发"),
                    ("reset", "重置临近"),
                    ("cpa_subscription_opened", "CPA 订阅后采样"),
                    ("cpa_subscription_closed", "CPA 关闭前采样"),
                ],
                default="scheduled",
                max_length=32,
            ),
        ),
    ]
