import monitor.fast_correction.rules
# Generated by Django 5.2.17 on 2026-09-05 16:32

import django.db.models.deletion
import monitor.billing_correction.rules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0048_cpa_collection_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings', name='fast_correction_rules',
            field=models.JSONField(blank=True, default=monitor.fast_correction.rules.default_fast_correction_rules, validators=[monitor.fast_correction.rules.validate_fast_correction_rules]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='long_context_correction_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='long_context_correction_rules',
            field=models.JSONField(blank=True, default=monitor.billing_correction.rules.default_long_context_correction_rules, validators=[monitor.billing_correction.rules.validate_long_context_correction_rules]),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='model_correction_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='model_correction_rules',
            field=models.JSONField(blank=True, default=monitor.billing_correction.rules.default_model_correction_rules, validators=[monitor.billing_correction.rules.validate_model_correction_rules]),
        ),
        migrations.AddField(
            model_name='participantapiusagesnapshot',
            name='raw_api_keys',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participantapiusagesnapshot',
            name='raw_facts_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantapiusagesnapshot',
            name='raw_request_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantapiusagesnapshot',
            name='raw_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='APIUsageRequestFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_log_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('model', models.CharField(blank=True, max_length=255)),
                ('service_tier', models.CharField(blank=True, max_length=32)),
                ('total_cost', models.CharField(max_length=96)),
                ('actual_cost', models.CharField(max_length=96)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cache_creation_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('long_context_billing_applied', models.BooleanField(blank=True, null=True)),
                ('api_key_id', models.BigIntegerField(default=0)),
                ('api_key_name', models.CharField(blank=True, max_length=255)),
                ('account_id', models.BigIntegerField()),
            ],
            options={
                'ordering': ['created_at', 'source_log_id'],
                'indexes': [models.Index(fields=['account_id', 'user_id', 'created_at'], name='api_usage_raw_user_time')],
                'constraints': [models.UniqueConstraint(fields=('account_id', 'source_log_id'), name='api_usage_account_source_log')],
            },
        ),
        migrations.CreateModel(
            name='ObservationBillingCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_capture', to='monitor.observation')),
            ],
        ),
        migrations.CreateModel(
            name='BillingUsageFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_log_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('model', models.CharField(blank=True, max_length=255)),
                ('service_tier', models.CharField(blank=True, max_length=32)),
                ('total_cost', models.CharField(max_length=96)),
                ('actual_cost', models.CharField(max_length=96)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cache_creation_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cache_read_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('long_context_billing_applied', models.BooleanField(blank=True, null=True)),
                ('api_key_id', models.BigIntegerField(default=0)),
                ('api_key_name', models.CharField(blank=True, max_length=255)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='monitor.observationbillingcapture')),
            ],
            options={
                'ordering': ['created_at', 'source_log_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='observationbillingcapture',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gte', models.F('started_at'))), name='billing_capture_time_order'),
        ),
        migrations.AddIndex(
            model_name='billingusagefact',
            index=models.Index(fields=['capture', 'user_id'], name='billing_capture_user'),
        ),
        migrations.AddConstraint(
            model_name='billingusagefact',
            constraint=models.UniqueConstraint(fields=('capture', 'source_log_id'), name='billing_capture_source_log'),
        ),
    ]
