# Generated by Django 5.2.17 on 2026-09-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0049_traceable_billing_corrections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('projects', models.JSONField(default=list)),
                ('endpoint', models.CharField(default='https://study.example.invalid', max_length=512)),
                ('interval_hours', models.PositiveSmallIntegerField(default=6)),
                ('gateway_only', models.BooleanField(default=False)),
                ('consent_hash', models.CharField(blank=True, max_length=64)),
                ('consent_at', models.DateTimeField(null=True)),
                ('config_revision', models.PositiveBigIntegerField(default=0)),
                ('identity_encrypted', models.TextField(blank=True)),
                ('report_revision', models.PositiveBigIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(null=True)),
                ('lease_token', models.CharField(blank=True, max_length=36)),
                ('lease_until', models.DateTimeField(null=True)),
                ('last_computed_at', models.DateTimeField(null=True)),
                ('last_sent_at', models.DateTimeField(null=True)),
                ('last_sent_endpoint', models.CharField(blank=True, max_length=512)),
                ('last_sent_hash', models.CharField(blank=True, max_length=64)),
                ('last_status', models.CharField(default='disabled', max_length=48)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchRequestComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_cost', models.CharField(max_length=96)),
                ('cache_creation_cost', models.CharField(max_length=96)),
                ('cache_read_cost', models.CharField(max_length=96)),
                ('output_cost', models.CharField(max_length=96)),
                ('fact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_components', to='monitor.billingusagefact')),
            ],
        ),
    ]
