# Generated by Django 5.2.17 on 2026-09-07 06:45

import uuid
from django.db import migrations, models


def upgrade_defaults_and_consent(apps, schema_editor):
    Settings = apps.get_model("monitor", "ResearchSettings")
    rows = Settings.objects.using(schema_editor.connection.alias)
    rows.filter(endpoint__in=["https://study.example.invalid", "https://study.example.invalid/"]).update(endpoint="https://codex.nightunderfly.online")
    # New report contents require fresh consent. Do not delete identity,
    # last-sent records, old contributions, or immutable usage facts.
    rows.update(enabled=False, consent_hash="", consent_at=None,
        config_revision=models.F("config_revision")+1, lease_token="", lease_until=None,
        next_run_at=None, summary={}, last_computed_at=None, last_status="disabled",
        last_error="科研已升级为无门槛原始证据共研，请阅读新告知后重新授权", failures=0)


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0050_opt_in_research'),
    ]

    operations = [
        migrations.RunPython(upgrade_defaults_and_consent, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='researchsettings',
            name='endpoint',
            field=models.CharField(default='https://codex.nightunderfly.online', max_length=512),
        ),
        migrations.CreateModel(
            name='ResearchEvidenceBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.BigIntegerField()),
                ('resets_at', models.DateTimeField()),
                ('source_fingerprints', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('sent_hashes', models.JSONField(default=dict)),
                ('archived_source', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account_id', 'resets_at'), name='research_batch_account_cycle')],
            },
        ),
    ]
