# Generated by Django 5.2.17 on 2026-09-08 01:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0051_pooled_research_raw_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPAAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('hint', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='participantsnapshot',
            name='cpa_contract_known',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sub2api_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CPAClaimPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('source_digest', models.CharField(max_length=64)),
                ('preview', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitor.cpaapikey')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpa_claim_plans', to='monitor.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CPAKeyBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='monitor.cpaapikey')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpa_bindings', to='monitor.participant')),
            ],
            options={
                'ordering': ['started_at', 'id'],
                'indexes': [models.Index(fields=['key', 'started_at', 'ended_at'], name='monitor_cpa_key_id_d216c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('key',), name='one_open_cpa_key_binding'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gt', models.F('started_at')), _connector='OR'), name='cpa_binding_positive_interval')],
            },
        ),
        migrations.CreateModel(
            name='CPAQuotaContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_at', models.DateTimeField()),
                ('pool_id_at_capture', models.BigIntegerField()),
                ('pool_name', models.CharField(max_length=160)),
                ('revision', models.PositiveBigIntegerField()),
                ('allocations', models.JSONField(default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpa_contracts', to='monitor.monitoredaccount')),
            ],
            options={
                'ordering': ['effective_at', 'id'],
                'indexes': [models.Index(fields=['account', 'effective_at'], name='monitor_cpa_account_71a032_idx')],
            },
        ),
    ]
