# Generated by Django 5.2.17 on 2026-09-08 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0052_cpa_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpakeybinding',
            name='claim',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monitor.cpaclaimplan'),
        ),
        migrations.CreateModel(
            name='CPAClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_claim', to='monitor.cpausageevent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='monitor.cpaclaimplan')),
            ],
        ),
    ]
