# Generated by Django 5.2.17 on 2026-09-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def initialize_owner_roles(apps, schema_editor):
    Account = apps.get_model("monitor", "MonitoredAccount")
    Allocation = apps.get_model("monitor", "PoolParticipant")
    Binding = apps.get_model("monitor", "CPAAccountOwnerBinding")
    now = timezone.now()
    for account in Account.objects.filter(provider="cpa"):
        owners = list(
            Allocation.objects.filter(
                pool_id=account.pool_id,
                participant__is_owner=True,
                participant__enabled=True,
            ).values_list("participant_id", flat=True)
        )
        if len(owners) == 1:
            Binding.objects.create(
                account_id=account.pk, participant_id=owners[0], started_at=now
            )


class Migration(migrations.Migration):
    dependencies = [
        ("monitor", "0053_cpa_claim_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cpaclaimplan",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="monitor.monitoredaccount",
            ),
        ),
        migrations.AlterField(
            model_name="cpaclaimplan",
            name="key",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="monitor.cpaapikey",
            ),
        ),
        migrations.CreateModel(
            name="CPAAccountOwnerBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpa_owner_bindings",
                        to="monitor.monitoredaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpa_owner_bindings",
                        to="monitor.participant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("account",),
                        name="one_open_cpa_account_owner",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True),
                            ("ended_at__gt", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="cpa_owner_positive_interval",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="cpaclaimplan",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(key__isnull=False, account__isnull=True)
                    | models.Q(key__isnull=True, account__isnull=False)
                ),
                name="cpa_claim_single_source",
            ),
        ),
        migrations.RunPython(initialize_owner_roles, migrations.RunPython.noop),
    ]
