# Generated by Django 5.2.17 on 2026-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0055_cpaquotaresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotapool',
            name='cpa_billing_anchor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotapool',
            name='cpa_billing_timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64),
        ),
    ]
